### ISSUE TITLE
Prepare 2020 edition

### ISSUE THREAD

**Issue by alexgavrisco** [Alexx-G/PAD-labs#8]
The best approach would be to keep labs structured as 3-4 mini projects and include course end-goals in these mini-projects.

Course end-goals:
- distribute systems introduction,
- brokers and messaging based agents,
- APIs role in distributed systems,
- remote execution (gRPC, Apache Thrift etc)
- cloud computing (why and when)
- importance of CI/CD for distributed systems

**TODOs**

- [ ] Update README to reflect the actual labs format
- [ ] Add an introduction document with definition of end goals and project examples
- [ ] Add document for each major milestone, it must include: definition of done, grading methodology

**Comment by alexgavrisco** [comment]
# Labs format

There are several option of the way labs can be organized.

## Option 1

3 mini-projects that are focused on a different set of course targets, there’s no requirement for projects to have a relationship between them. Each project is graded separately.

## Option 2

A single project, split in 3-4 milestones with focus on a specific set requirements for each milestone. The key difference from Option 1 is to get a more complex project in the end, but keep focused milestones to achieve all goals. Each milestone is going to be graded, considering previous milestones, overall project status and a final grade for the project.

## Option 3

5-6 tiny labs that are going to be focused on a single goal. While this is the easiest option to implement and grade, it’s probably the least exciting and productive. Keeping labs too focused, increases the chances of loosing the received knowledge.

**Comment by alexgavrisco** [comment]
So, the final format is going to be:

- A single project idea split into 3 major milestones;
- Each milestone must have a clear "definition of done" and a deadline so it can be graded separately (university requirements);

### Project Requirements

- (almost) no platform restrictions - any programming language can be used, restriction being a sane standard library and networking/concurrency primitives;
- students must define themselves what problem their project is going to solve, the project must be complex enough so it can be implemented as a distributed system;
  - a list of project examples to be provided;
- unless stated otherwise, libraries usage is allowed;

### Project Milestones

1. Messaging based agents
1.1 Decoupling communication between services using brokers
1.2 Advanced message protocols/RPC - Thrift/gRPC etc
2. Web services - HTTP recap, RESTful APIs, web-proxy, caching
3. Cloud migration & DevOps principles
